<hr style="clear: both;">
<div class="testimonials">
    <h3><font color="#6d6d6d">Форма обратной связи</font></h3>
    <form action="index.html" class="contact">
        <fieldset class="contact-inner">
            <p class="contact-input">
                <input type="text" name="name" placeholder="Ваше имя…" required>
            </p>

            <p class="contact-input">
                <input type="text" name="email" placeholder="Ваш e-mail…" required>
            </p>

            <p class="contact-input">
                <textarea name="message" placeholder="Сообщение…" required></textarea>
            </p>

            <p class="contact-submit">
                <input type="submit" value="Отправить">
            </p>
        </fieldset>
    </form>
</div>
<div class="meaning">
    <h3><font color="#6d6d6d">Контактные данные</font></h3>
    <table class="addres">
        <tr><td class="left">
                <b>Адрес:</b>
            </td>
            <td class="right">  г. Невинномысск, ул. Павлова, д.21<br />
                г. Ставрополь, пер. Восточный, д.4<br />
                г. Краснодар
            </td>
        </tr>
        <tr>
            <td class="left">
                <b>Телефон:</b>
            </td>
            <td class="right"> г. Невинномысск, г. Ставрополь<br />
                +7-903-440-440-5<br />
                +7-918-762-97-67<br />
                г. Краснодар<br />
                +7-964-894-72-03<br />
            </td>
        <tr>
            <td class="left">
                <b>E-mail: </b>
            </td>
            <td class="right"> 
                psiholog-antipin@yandex.ru
            </td>
        </tr>

        <tr>
            <td class="left">
                <b>Соц. сети: </b>
            </td>
            <td class="right"> 
                <a href="http://vk.com/id89167262" target="_blank"><img src="../img/icon_vk.png" title="Вконтакте" style="width: 30px;"></a>
                <a href="http://odnoklassniki.ru/profile/406600371309" target="_blank"><img src="../img/icon_odnoklassniki.png" title="Одноклассники" style="width: 30px;"></a>
                <a href="https://facebook.com/anatoliy.antipin" target="_blank"><img src="../img/icon_fb.png" title="Facebook" style="width: 30px;"></a>
            </td>
        </tr>
    </table>
</div>