<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content='психолог, психолог Невинномысск Ставрополь Краснодар, Антипин Анатолий Иванович, психология Невинномысск, психологическая помощь' name='keywords'/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="/img/icon.ico" >
            <link href='http://fonts.googleapis.com/css?family=Roboto+Slab&subset=cyrillic,cyrillic-ext,latin' rel='stylesheet' type='text/css'>
                <title>Психолог Антипин Анатолий Иванович</title>
                <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
                <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
                <script src="/js/masonry.pkgd.min.js"></script>
                </head>
                <body>
                    <div id="containerr">
                        <!-- #header -->
                        <div id="header">
                            <div class="logo">
                                <a href="/" style="text-decoration: none;">
                                    <img src="/img/logo.png" class="img_logo" />
                                    <table>
                                        <tr><td><h3 style="margin: 0px;">Антипин</h3></td></tr>
                                        <tr><td><h5>Анатолий Иванович</h5></td></tr>
                                    </table>
                                </a>
                            </div>
                            <div class="author">
                                <table>
                                    <tr><td><h3 style="margin: 0px;">Психолог-консультант</h3></td></tr>
                                    <tr><td><h4>Психологическое консультирование и коррекция</h4></td></tr>
                                </table>
                            </div>
                        </div>
                        <!-- / #header -->
                        <div id="navcontainer">
                            <ul id="navlist">
                                <li><a href="/">Главная</a></li>
                                <li><a href="<?php
                                    echo $this->url(
                                            array(
                                        'controller' => 'index',
                                        'action'     => 'about'
                                            ), 'default', true)
                                    ?>">Обо мне</a></li>
                                <li><a href="<?php
                                    echo $this->url(
                                            array(
                                        'controller' => 'index',
                                        'action'     => 'answer'
                                            ), 'default', true)
                                    ?>">Вопрос-ответ</a></li>
                                <li><a href="<?php
                                    echo $this->url(
                                            array(
                                        'controller' => 'index',
                                        'action'     => 'contacts'
                                            ), 'default', true)
                                    ?>">Контакты</a></li>
                            </ul>
                        </div>
                        <!--<div class="headerPic"><img src="../img/headerBackground.jpg" alt="Header picture" width="800" height="269" /></div>-->
                        <!-- #mainContent -->
                        <div id="mainContent">
                            <div class="copyrightTemplate">
                                <?php echo $this->layout()->content ?>
                            </div>
                        </div>
                        <div class="clearer"></div>
                        <!-- / #mainContent -->
                        <!-- #footer -->
                        <div id="footer">
                            <div class="fcenter">
                                <div class="fleft"><p>&copy; <a href="/">psiholog-antipin.ru</a> 2013 г.</p></div>

                                <div class=metrica>
                                    <!-- Yandex.Metrika informer -->
                                    <a href="https://metrika.yandex.ru/stat/?id=25543823&amp;from=informer"
                                       target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/25543823/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                                                                        style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try {
                                                                                    Ya.Metrika.informer({i: this, id: 25543823, lang: 'ru'});
                                                                                    return false
                                                                                } catch (e) {
                                                                                }"/></a>
                                    <!-- /Yandex.Metrika informer -->

                                    <!-- Yandex.Metrika counter -->
                                    <script type="text/javascript">
                                        (function(d, w, c) {
                                            (w[c] = w[c] || []).push(function() {
                                                try {
                                                    w.yaCounter25543823 = new Ya.Metrika({id: 25543823,
                                                        webvisor: true,
                                                        clickmap: true,
                                                        trackLinks: true,
                                                        accurateTrackBounce: true});
                                                } catch (e) {
                                                }
                                            });

                                            var n = d.getElementsByTagName("script")[0],
                                                    s = d.createElement("script"),
                                                    f = function() {
                                                        n.parentNode.insertBefore(s, n);
                                                    };
                                            s.type = "text/javascript";
                                            s.async = true;
                                            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

                                            if (w.opera == "[object Opera]") {
                                                d.addEventListener("DOMContentLoaded", f, false);
                                            } else {
                                                f();
                                            }
                                        })(document, window, "yandex_metrika_callbacks");
                                    </script>
                                    <noscript><div><img src="//mc.yandex.ru/watch/25543823" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
                                    <!-- /Yandex.Metrika counter -->

                                </div>
                            </div>
                        </div>

                        <!-- / #footer -->
                    </div>
                </body>
                </html>

                <script>

                    $(document).ready(function() {
                        var link = window.location.pathname;
                        $('#navlist li a[href="' + link + '"]').parent().addClass('active');
                    });
                </script>