<h1>Admin</h1>
<? if ( $this->error ): ?>
        <div class="error">
            <?= $this->error; ?>
        </div>
    <? endif; ?>
<form method="post">

    <label>
        <span>Имя пользователя:</span>
        <input type="text" name="name"/>
    </label>
    <br />
    <label>
        <span>Пароль:</span>
        <input type="password" name="password"/>
    </label>
    <br/>    
    <br/>

    <div class="btn" style="width: 50px;" onclick="$(this).parents('form').submit()">Войти</div>
</form>